#!/usr/bin/env node
/**
 * Creates the MySQL database and app user, writes backend/.env, and applies database/schema.sql.
 *
 * Run from the repository root after: cd backend && npm install
 *
 *   node scripts/setup.js
 */

import readline from 'readline/promises';
import { stdin as input } from 'process';
import { createRequire } from 'module';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { randomBytes } from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const require = createRequire(import.meta.url);
let mysql2;
try {
  mysql2 = require(resolve(ROOT, 'backend/node_modules/mysql2/promise'));
} catch {
  console.error('\n[ERROR] mysql2 not found. Run: cd backend && npm install\n');
  process.exit(1);
}

const mysql = require(resolve(ROOT, 'backend/node_modules/mysql2'));

function generatePassword(length = 20) {
  return randomBytes(length).toString('base64url').slice(0, length);
}

function writeEnv(values) {
  const envPath = resolve(ROOT, 'backend/.env');
  const lines = [
    '# Generated by scripts/setup.js — do not commit',
    '',
    'NODE_ENV=development',
    `PORT=${values.port}`,
    '',
    `DATABASE_HOST=${values.dbHost}`,
    `DATABASE_PORT=${values.dbPort}`,
    `DATABASE_USER=${values.appUser}`,
    `DATABASE_PASSWORD=${values.appPassword}`,
    `DATABASE_NAME=${values.dbName}`,
    '',
    `JWT_SECRET=${generatePassword(40)}`,
    'JWT_EXPIRES_IN=7d',
    '',
    'POKEAPI_BASE_URL=https://pokeapi.co/api/v2',
  ];
  writeFileSync(envPath, `${lines.join('\n')}\n`, 'utf8');
  return envPath;
}

const rl = readline.createInterface({ input, output: process.stdout });

console.log('\nPokémon Spanbouer — database setup\n');
console.log('You need a MySQL account with CREATE USER and GRANT (often root).\n');

const adminHost =
  (await rl.question('MySQL host [127.0.0.1]: ')) || '127.0.0.1';
const adminPortStr = (await rl.question('MySQL port [3306]: ')) || '3306';
const adminUser = (await rl.question('Admin username [root]: ')) || 'root';
const adminPassword = await rl.question('Admin password: ');
const dbName =
  (await rl.question('Database name [pokemon_spanbouer]: ')) ||
  'pokemon_spanbouer';
const appUser =
  (await rl.question('App database user [pokemon_app]: ')) || 'pokemon_app';
const appPortStr =
  (await rl.question('Backend HTTP port [3001]: ')) || '3001';

const appPassword = generatePassword();
const adminPort = parseInt(adminPortStr, 10);

console.log('\nConnecting…');

let adminConn;
try {
  adminConn = await mysql2.createConnection({
    host: adminHost,
    port: adminPort,
    user: adminUser,
    password: adminPassword,
    multipleStatements: true,
  });
} catch (err) {
  console.error('\n[ERROR] Could not connect to MySQL.');
  console.error(err.message, '\n');
  rl.close();
  process.exit(1);
}

console.log('Connected.\n');

await adminConn.query(
  `CREATE DATABASE IF NOT EXISTS \`${dbName}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`
);

console.log(`Creating database user "${appUser}"…`);
const pwdLiteral = mysql.escape(appPassword);
await adminConn.query(`DROP USER IF EXISTS \`${appUser}\`@\`${adminHost}\``);
await adminConn.query(
  `CREATE USER \`${appUser}\`@\`${adminHost}\` IDENTIFIED BY ${pwdLiteral}`
);
await adminConn.query(
  `GRANT ALL PRIVILEGES ON \`${dbName}\`.* TO \`${appUser}\`@\`${adminHost}\``
);
await adminConn.query('FLUSH PRIVILEGES');

const schemaPath = resolve(ROOT, 'database/schema.sql');
if (existsSync(schemaPath)) {
  console.log('Applying database/schema.sql…');
  await adminConn.query(`USE \`${dbName}\``);
  const schemaSql = readFileSync(schemaPath, 'utf8');
  await adminConn.query(schemaSql);
} else {
  console.log('database/schema.sql not found — skipped.');
}

await adminConn.end();

const envPath = writeEnv({
  dbHost: adminHost,
  dbPort: adminPort,
  appUser,
  appPassword,
  dbName,
  port: appPortStr,
});

rl.close();

console.log('\nDone.\n');
console.log(`  Database : ${dbName} @ ${adminHost}:${adminPort}`);
console.log(`  DB user  : ${appUser}`);
console.log(`  DB pass  : ${appPassword}`);
console.log(`  Env file : ${envPath}`);
console.log('\nCopy the DB user and password into README (Assessor setup).');
console.log('.env is git-ignored; the README must list credentials for the assessor.\n');
console.log('Next: cd backend && npm run dev');
console.log('      cd frontend && npm install && npm run dev\n');
